Repository acm-ucr/star-wars-website, pull requests merged in 2024-10, with the labels that each got.

#26 Finished Navbar
  public/frame/navframe.svg
  public/frame/navjoinframe.svg
  src/app/board/page.tsx
  src/app/layout.tsx
  src/components/Navigation.tsx
  src/data/navigation.ts
  tailwind.config.ts
Labels: Ready to Review

#27 Finished title component 2
  public/frame/title2smallframe.svg
  public/starframeIcon.svg
  src/components/Header.tsx
Labels: good first issue, Ready to Review

#33 404 Page
  public/frame/404homeframe.svg
  src/app/not-found.tsx
Labels: Ready to Review

#34 Create landing
  src/components/Landing.tsx
Labels: Ready to Review

#29 finished About
  public/swNameOnly.svg
  src/components/About.tsx
Labels: good first issue, Ready to Review

#31 Fixed Title component
  src/components/Title.tsx
Labels: good first issue, Ready to Review

#35 Finished Board Cards and Fixed Nav
  public/frame/cardframe.svg
  src/components/Board.tsx
  src/components/Card.tsx
  src/components/Navigation.tsx
  src/data/board.ts
Labels: bug, Ready to Review

#28 Added the button component. Set the backround to black for now to sho…
  src/app/layout.tsx
  src/components/Button.tsx
  src/components/Landing.tsx
Labels: good first issue, invalid, Ready to Review

#30 What component
  public/swStar.svg
  src/components/What.tsx
Labels: Ready to Review

#32 Completed Join Component
  public/frame/discord.svg
  public/frame/email.svg
  public/frame/highlander.svg
  public/frame/instagram.svg
  public/frame/joinframe1.svg
  public/frame/star.svg
  src/components/Join.tsx
Labels: good first issue, Ready to Review

#41 Finished Club History Landing (w/out background)
  src/app/history/page.tsx
  src/components/history/HistoryLanding.tsx
Labels: Ready to Review

#42 Finished Gallery landing
  src/app/gallery/page.tsx
  src/components/gallery/Gallery.tsx
Labels: Ready to Review

#43 Add Creation Component
  src/app/gallery/page.tsx
  src/components/gallery/Creation.tsx
  src/components/gallery/Gallery.tsx
  src/data/creation.ts
Labels: Ready to Review
